IF "%TARGET%"=="" SET TARGET=CORTEXM
IF "%DERIVATE%"=="" SET DERIVATE=S32K34X
IF "%TOOLCHAIN%"=="" SET TOOLCHAIN=multi
IF [%TOOLPATH_COMPILER%]==[] SET TOOLPATH_COMPILER=C:\work\workspace\ACP-8.8.6_S32K34X\tools\toolchain
IF [%TRESOS_BASE%]==[] SET TRESOS_BASE=C:\work\workspace\ACP-8.8.6_S32K34X\Tresos
IF [%PLUGINS_BASE%]==[] set PLUGINS_BASE=%TRESOS_BASE%\plugins
