IF "%TARGET%"=="" SET TARGET=CORTEXM
IF "%DERIVATE%"=="" SET DERIVATE=S32K34X
IF "%TOOLCHAIN%"=="" SET TOOLCHAIN=multi
IF [%TOOLPATH_COMPILER%]==[] SET TOOLPATH_COMPILER=C:\ghs\comp_202114
IF [%TRESOS_BASE%]==[] SET TRESOS_BASE=C:\EB\tresos
IF [%PLUGINS_BASE%]==[] set PLUGINS_BASE=%TRESOS_BASE%\plugins
