/**
 * \file
 *
 * \brief AUTOSAR Demo_PSA
 *
 * This file contains the implementation of the AUTOSAR
 * module Demo_PSA.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2020 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 *  MISRA deviation report:
 *  - This file violates MISRA-C:2004, Rule 19.6:
 *       "#undef shall not be used"
 *    Reason:
 *       The specification document explicitely describes this mechanism.
 *  - This file violates MISRA-C:2004, Rule 19.15:
 *       "Precautions shall be taken in order to prevent the contents
 *        of a header file being included twice."
 *    Reason:
 *       This file needs to be included more than once in a compilation unit
 */

/*==================[inclusions]=============================================*/

/*==================[macros]=================================================*/

/*------------------[Autosar vendor identification]--------------------------*/

#if (!defined MEM_VENDOR_ID)
/** \brief Autosar module vendor identification
 **
 ** Vendor ID of the dedicated implementation of this module according
 ** to the AUTOSAR vendor list. */
#define MEM_VENDOR_ID 1U /* Elektrobit Automotive GmbH */
#endif

/*------------------[AUTOSAR release version identification]-----------------*/

#if (!defined MEM_AR_RELEASE_MAJOR_VERSION)
/** \brief definition of the AUTOSAR release major version of the specification */
#define MEM_AR_RELEASE_MAJOR_VERSION 1U
#endif

#if (!defined MEM_AR_RELEASE_MINOR_VERSION)
/** \brief definition of a AUTOSAR release minor version of the specification */
#define MEM_AR_RELEASE_MINOR_VERSION 1U
#endif

#if (!defined MEM_AR_RELEASE_PATCH_VERSION)
/** \brief definition of a AUTOSAR release patch version of the specification */
#define MEM_AR_RELEASE_PATCH_VERSION 0U
#endif

/*------------------[Autosar software version]-------------------------------*/

#if (!defined MEM_SW_MAJOR_VERSION)
/** \brief definition of the major version of this implementation */
#define MEM_SW_MAJOR_VERSION 1U
#endif

#if (!defined MEM_SW_MINOR_VERSION)
/** \brief definition of a minor version of this implementation */
#define MEM_SW_MINOR_VERSION 1U
#endif

#if (!defined MEM_SW_PATCH_VERSION)
/** \brief definition of a patch version of this implementation */
#define MEM_SW_PATCH_VERSION 0U
#endif

/*------------------[MemMap error checking]----------------------------------*/

#if 0 /* to be able to use #elif for every module */

/*------------------[Start of a module]--------------------------------------*/

#elif (defined EBSTUBS_START_SEC_CODE)
  #undef EBSTUBS_START_SEC_CODE
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CODE)
  #undef EBSTUBS_STOP_SEC_CODE
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_APPL_CODE || defined EBSTUBS_START_SEC_CALLOUT_CODE)
  #undef EBSTUBS_START_SEC_APPL_CODE
  #undef EBSTUBS_START_SEC_CALLOUT_CODE
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_APPL_CODE || defined EBSTUBS_STOP_SEC_CALLOUT_CODE)
  #undef EBSTUBS_STOP_SEC_APPL_CODE
  #undef EBSTUBS_STOP_SEC_CALLOUT_CODE
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_NOINIT_BOOLEAN || defined EBSTUBS_START_SEC_VAR_NO_INIT_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_NOINIT_BOOLEAN
  #undef EBSTUBS_START_SEC_VAR_NO_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_NOINIT_BOOLEAN || defined EBSTUBS_STOP_SEC_VAR_NO_INIT_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_NOINIT_BOOLEAN
  #undef EBSTUBS_STOP_SEC_VAR_NO_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_NOINIT_8BIT || defined EBSTUBS_START_SEC_VAR_NO_INIT_8)
  #undef EBSTUBS_START_SEC_VAR_NOINIT_8BIT
  #undef EBSTUBS_START_SEC_VAR_NO_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_NOINIT_8BIT || defined EBSTUBS_STOP_SEC_VAR_NO_INIT_8)
  #undef EBSTUBS_STOP_SEC_VAR_NOINIT_8BIT
  #undef EBSTUBS_STOP_SEC_VAR_NO_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_NOINIT_16BIT || defined EBSTUBS_START_SEC_VAR_NO_INIT_16)
  #undef EBSTUBS_START_SEC_VAR_NOINIT_16BIT
  #undef EBSTUBS_START_SEC_VAR_NO_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_NOINIT_16BIT || defined EBSTUBS_STOP_SEC_VAR_NO_INIT_16)
  #undef EBSTUBS_STOP_SEC_VAR_NOINIT_16BIT
  #undef EBSTUBS_STOP_SEC_VAR_NO_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_NOINIT_32BIT || defined EBSTUBS_START_SEC_VAR_NO_INIT_32)
  #undef EBSTUBS_START_SEC_VAR_NOINIT_32BIT
  #undef EBSTUBS_START_SEC_VAR_NO_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_NOINIT_32BIT || defined EBSTUBS_STOP_SEC_VAR_NO_INIT_32)
  #undef EBSTUBS_STOP_SEC_VAR_NOINIT_32BIT
  #undef EBSTUBS_STOP_SEC_VAR_NO_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_NOINIT_UNSPECIFIED || defined EBSTUBS_START_SEC_VAR_NO_INIT_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef EBSTUBS_START_SEC_VAR_NO_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_NOINIT_UNSPECIFIED || defined EBSTUBS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef EBSTUBS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_INIT_BOOLEAN || defined EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN || defined EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_INIT_8BIT || defined EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8 || defined EBSTUBS_START_SEC_VAR_POWER_ON_INIT_8)
  #undef EBSTUBS_START_SEC_VAR_POWER_ON_INIT_8BIT
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
  #undef EBSTUBS_START_SEC_VAR_POWER_ON_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_8BIT || defined EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8 || defined EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_8)
  #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_8BIT
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
  #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_INIT_16BIT || defined EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16 || defined EBSTUBS_START_SEC_VAR_POWER_ON_INIT_16)
  #undef EBSTUBS_START_SEC_VAR_POWER_ON_INIT_16BIT
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
  #undef EBSTUBS_START_SEC_VAR_POWER_ON_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_16BIT || defined EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16 || defined EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_16)
  #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_16BIT
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
  #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_INIT_32BIT || defined EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32 || defined EBSTUBS_START_SEC_VAR_POWER_ON_INIT_32)
  #undef EBSTUBS_START_SEC_VAR_POWER_ON_INIT_32BIT
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
  #undef EBSTUBS_START_SEC_VAR_POWER_ON_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_32BIT || defined EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32 || defined EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_32)
  #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_32BIT
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
  #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED || defined EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED || defined EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_BOOLEAN || defined EBSTUBS_START_SEC_VAR_FAST_INIT_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_FAST_BOOLEAN
  #undef EBSTUBS_START_SEC_VAR_FAST_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_BOOLEAN || defined EBSTUBS_STOP_SEC_VAR_FAST_INIT_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_BOOLEAN
  #undef EBSTUBS_STOP_SEC_VAR_FAST_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_8BIT || defined EBSTUBS_START_SEC_VAR_FAST_INIT_8)
  #undef EBSTUBS_START_SEC_VAR_FAST_8BIT
  #undef EBSTUBS_START_SEC_VAR_FAST_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_8BIT || defined EBSTUBS_STOP_SEC_VAR_FAST_INIT_8)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_8BIT
  #undef EBSTUBS_STOP_SEC_VAR_FAST_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_16BIT || defined EBSTUBS_START_SEC_VAR_FAST_INIT_16)
  #undef EBSTUBS_START_SEC_VAR_FAST_16BIT
  #undef EBSTUBS_START_SEC_VAR_FAST_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_16BIT || defined EBSTUBS_STOP_SEC_VAR_FAST_INIT_16)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_16BIT
  #undef EBSTUBS_STOP_SEC_VAR_FAST_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_32BIT || defined EBSTUBS_START_SEC_VAR_FAST_INIT_32)
  #undef EBSTUBS_START_SEC_VAR_FAST_32BIT
  #undef EBSTUBS_START_SEC_VAR_FAST_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_32BIT || defined EBSTUBS_STOP_SEC_VAR_FAST_INIT_32)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_32BIT
  #undef EBSTUBS_STOP_SEC_VAR_FAST_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_UNSPECIFIED || defined EBSTUBS_START_SEC_VAR_FAST_INIT_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_FAST_UNSPECIFIED
  #undef EBSTUBS_START_SEC_VAR_FAST_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_UNSPECIFIED || defined EBSTUBS_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_UNSPECIFIED
  #undef EBSTUBS_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_BOOLEAN || defined EBSTUBS_START_SEC_INTERNAL_VAR_INIT_BOOLEAN)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_BOOLEAN
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_BOOLEAN || defined EBSTUBS_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_BOOLEAN
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_8BIT || defined EBSTUBS_START_SEC_INTERNAL_VAR_INIT_8)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_8BIT
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_8BIT || defined EBSTUBS_STOP_SEC_INTERNAL_VAR_INIT_8)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_8BIT
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_16BIT || defined EBSTUBS_START_SEC_INTERNAL_VAR_INIT_16)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_16BIT
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_16BIT || defined EBSTUBS_STOP_SEC_INTERNAL_VAR_INIT_16)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_16BIT
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_32BIT || defined EBSTUBS_START_SEC_INTERNAL_VAR_INIT_32)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_32BIT
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_32BIT || defined EBSTUBS_STOP_SEC_INTERNAL_VAR_INIT_32)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_32BIT
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_UNSPECIFIED || defined EBSTUBS_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_UNSPECIFIED
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_UNSPECIFIED || defined EBSTUBS_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_UNSPECIFIED
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_BOOLEAN || defined EBSTUBS_START_SEC_VAR_INIT_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_BOOLEAN
  #undef EBSTUBS_START_SEC_VAR_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_BOOLEAN || defined EBSTUBS_STOP_SEC_VAR_INIT_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_BOOLEAN
  #undef EBSTUBS_STOP_SEC_VAR_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_8BIT || defined EBSTUBS_START_SEC_VAR_INIT_8)
  #undef EBSTUBS_START_SEC_VAR_8BIT
  #undef EBSTUBS_START_SEC_VAR_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_8BIT || defined EBSTUBS_STOP_SEC_VAR_INIT_8)
  #undef EBSTUBS_STOP_SEC_VAR_8BIT
  #undef EBSTUBS_STOP_SEC_VAR_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_16BIT || defined EBSTUBS_START_SEC_VAR_INIT_16)
  #undef EBSTUBS_START_SEC_VAR_16BIT
  #undef EBSTUBS_START_SEC_VAR_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_16BIT || defined EBSTUBS_STOP_SEC_VAR_INIT_16)
  #undef EBSTUBS_STOP_SEC_VAR_16BIT
  #undef EBSTUBS_STOP_SEC_VAR_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_32BIT || defined EBSTUBS_START_SEC_VAR_INIT_32)
  #undef EBSTUBS_START_SEC_VAR_32BIT
  #undef EBSTUBS_START_SEC_VAR_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_32BIT || defined EBSTUBS_STOP_SEC_VAR_INIT_32)
  #undef EBSTUBS_STOP_SEC_VAR_32BIT
  #undef EBSTUBS_STOP_SEC_VAR_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_UNSPECIFIED || defined EBSTUBS_START_SEC_VAR_INIT_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_UNSPECIFIED
  #undef EBSTUBS_START_SEC_VAR_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_UNSPECIFIED || defined EBSTUBS_STOP_SEC_VAR_INIT_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_UNSPECIFIED
  #undef EBSTUBS_STOP_SEC_VAR_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CONST_BOOLEAN)
  #undef EBSTUBS_START_SEC_CONST_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CONST_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_CONST_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CONST_8BIT || defined EBSTUBS_START_SEC_CONST_8)
  #undef EBSTUBS_START_SEC_CONST_8BIT
  #undef EBSTUBS_START_SEC_CONST_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CONST_8BIT || defined EBSTUBS_STOP_SEC_CONST_8)
  #undef EBSTUBS_STOP_SEC_CONST_8BIT
  #undef EBSTUBS_STOP_SEC_CONST_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CONST_16BIT || defined EBSTUBS_START_SEC_CONST_16)
  #undef EBSTUBS_START_SEC_CONST_16BIT
  #undef EBSTUBS_START_SEC_CONST_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CONST_16BIT || defined EBSTUBS_STOP_SEC_CONST_16)
  #undef EBSTUBS_STOP_SEC_CONST_16BIT
  #undef EBSTUBS_STOP_SEC_CONST_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CONST_32BIT || defined EBSTUBS_START_SEC_CONST_32)
  #undef EBSTUBS_START_SEC_CONST_32BIT
  #undef EBSTUBS_START_SEC_CONST_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CONST_32BIT || defined EBSTUBS_STOP_SEC_CONST_32)
  #undef EBSTUBS_STOP_SEC_CONST_32BIT
  #undef EBSTUBS_STOP_SEC_CONST_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CONST_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_CONST_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CONST_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_CONST_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CALIB_BOOLEAN)
  #undef EBSTUBS_START_SEC_CALIB_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CALIB_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_CALIB_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CALIB_8BIT || defined EBSTUBS_START_SEC_CALIB_8)
  #undef EBSTUBS_START_SEC_CALIB_8BIT
  #undef EBSTUBS_START_SEC_CALIB_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CALIB_8BIT || defined EBSTUBS_STOP_SEC_CALIB_8)
  #undef EBSTUBS_STOP_SEC_CALIB_8BIT
  #undef EBSTUBS_STOP_SEC_CALIB_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CALIB_16BIT || defined EBSTUBS_START_SEC_CALIB_16)
  #undef EBSTUBS_START_SEC_CALIB_16BIT
  #undef EBSTUBS_START_SEC_CALIB_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CALIB_16BIT || defined EBSTUBS_STOP_SEC_CALIB_16)
  #undef EBSTUBS_STOP_SEC_CALIB_16BIT
  #undef EBSTUBS_STOP_SEC_CALIB_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CALIB_32BIT || defined EBSTUBS_START_SEC_CALIB_32)
  #undef EBSTUBS_START_SEC_CALIB_32BIT
  #undef EBSTUBS_START_SEC_CALIB_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CALIB_32BIT || defined EBSTUBS_STOP_SEC_CALIB_32)
  #undef EBSTUBS_STOP_SEC_CALIB_32BIT
  #undef EBSTUBS_STOP_SEC_CALIB_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CALIB_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_CALIB_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CALIB_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_CALIB_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CARTO_BOOLEAN)
  #undef EBSTUBS_START_SEC_CARTO_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CARTO_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_CARTO_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CARTO_8BIT || defined EBSTUBS_START_SEC_CARTO_8)
  #undef EBSTUBS_START_SEC_CARTO_8BIT
  #undef EBSTUBS_START_SEC_CARTO_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CARTO_8BIT || defined EBSTUBS_STOP_SEC_CARTO_8)
  #undef EBSTUBS_STOP_SEC_CARTO_8BIT
  #undef EBSTUBS_STOP_SEC_CARTO_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CARTO_16BIT || defined EBSTUBS_START_SEC_CARTO_16)
  #undef EBSTUBS_START_SEC_CARTO_16BIT
  #undef EBSTUBS_START_SEC_CARTO_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CARTO_16BIT || defined EBSTUBS_STOP_SEC_CARTO_16)
  #undef EBSTUBS_STOP_SEC_CARTO_16BIT
  #undef EBSTUBS_STOP_SEC_CARTO_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CARTO_32BIT || defined EBSTUBS_START_SEC_CARTO_32)
  #undef EBSTUBS_START_SEC_CARTO_32BIT
  #undef EBSTUBS_START_SEC_CARTO_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CARTO_32BIT || defined EBSTUBS_STOP_SEC_CARTO_32)
  #undef EBSTUBS_STOP_SEC_CARTO_32BIT
  #undef EBSTUBS_STOP_SEC_CARTO_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CARTO_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_CARTO_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CARTO_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_CARTO_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_CONFIG_DATA_BOOLEAN || defined EBSTUBS_START_SEC_CONFIG_DATA_BOOLEAN)
  #undef EBSTUBS_START_CONFIG_DATA_BOOLEAN
  #undef EBSTUBS_START_SEC_CONFIG_DATA_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_CONFIG_DATA_BOOLEAN || defined EBSTUBS_STOP_SEC_CONFIG_DATA_BOOLEAN)
  #undef EBSTUBS_STOP_CONFIG_DATA_BOOLEAN
  #undef EBSTUBS_STOP_SEC_CONFIG_DATA_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_CONFIG_DATA_8BIT || defined EBSTUBS_START_SEC_CONFIG_DATA_8)
  #undef EBSTUBS_START_CONFIG_DATA_8BIT
  #undef EBSTUBS_START_SEC_CONFIG_DATA_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_CONFIG_DATA_8BIT || defined EBSTUBS_STOP_SEC_CONFIG_DATA_8)
  #undef EBSTUBS_STOP_CONFIG_DATA_8BIT
  #undef EBSTUBS_STOP_SEC_CONFIG_DATA_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_CONFIG_DATA_16BIT || defined EBSTUBS_START_SEC_CONFIG_DATA_16)
  #undef EBSTUBS_START_CONFIG_DATA_16BIT
  #undef EBSTUBS_START_SEC_CONFIG_DATA_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_CONFIG_DATA_16BIT || defined EBSTUBS_STOP_SEC_CONFIG_DATA_16)
  #undef EBSTUBS_STOP_CONFIG_DATA_16BIT
  #undef EBSTUBS_STOP_SEC_CONFIG_DATA_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_CONFIG_DATA_32BIT || defined EBSTUBS_START_SEC_CONFIG_DATA_32)
  #undef EBSTUBS_START_CONFIG_DATA_32BIT
  #undef EBSTUBS_START_SEC_CONFIG_DATA_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_CONFIG_DATA_32BIT || defined EBSTUBS_STOP_SEC_CONFIG_DATA_32)
  #undef EBSTUBS_STOP_CONFIG_DATA_32BIT
  #undef EBSTUBS_STOP_SEC_CONFIG_DATA_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_CONFIG_DATA_UNSPECIFIED || defined EBSTUBS_START_SEC_CONFIG_DATA_UNSPECIFIED)
  #undef EBSTUBS_START_CONFIG_DATA_UNSPECIFIED
  #undef EBSTUBS_START_SEC_CONFIG_DATA_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_CONFIG_DATA_UNSPECIFIED || defined EBSTUBS_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
  #undef EBSTUBS_STOP_CONFIG_DATA_UNSPECIFIED
  #undef EBSTUBS_STOP_SEC_CONFIG_DATA_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_CLEARED_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_CLEARED_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_CLEARED_8)
  #undef EBSTUBS_START_SEC_VAR_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_CLEARED_8)
  #undef EBSTUBS_STOP_SEC_VAR_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_CLEARED_16)
  #undef EBSTUBS_START_SEC_VAR_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_CLEARED_16)
  #undef EBSTUBS_STOP_SEC_VAR_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_CLEARED_32)
  #undef EBSTUBS_START_SEC_VAR_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_CLEARED_32)
  #undef EBSTUBS_STOP_SEC_VAR_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_8)
  #undef EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_8)
  #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_16)
  #undef EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_16)
  #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_32)
  #undef EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_32)
  #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_NO_INIT_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_FAST_NO_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_NO_INIT_8)
  #undef EBSTUBS_START_SEC_VAR_FAST_NO_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_NO_INIT_8)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_NO_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_NO_INIT_16)
  #undef EBSTUBS_START_SEC_VAR_FAST_NO_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_NO_INIT_16)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_NO_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_NO_INIT_32)
  #undef EBSTUBS_START_SEC_VAR_FAST_NO_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_NO_INIT_32)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_NO_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_CLEARED_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_FAST_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_CLEARED_8)
  #undef EBSTUBS_START_SEC_VAR_FAST_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_CLEARED_8)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_CLEARED_16)
  #undef EBSTUBS_START_SEC_VAR_FAST_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_CLEARED_16)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_CLEARED_32)
  #undef EBSTUBS_START_SEC_VAR_FAST_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_CLEARED_32)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_POWER_ON_CLEARED_8)
  #undef EBSTUBS_START_SEC_VAR_FAST_POWER_ON_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_POWER_ON_CLEARED_16)
  #undef EBSTUBS_START_SEC_VAR_FAST_POWER_ON_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_POWER_ON_CLEARED_32)
  #undef EBSTUBS_START_SEC_VAR_FAST_POWER_ON_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_POWER_ON_INIT_8)
  #undef EBSTUBS_START_SEC_VAR_FAST_POWER_ON_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_INIT_8)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_POWER_ON_INIT_16)
  #undef EBSTUBS_START_SEC_VAR_FAST_POWER_ON_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_INIT_16)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_POWER_ON_INIT_32)
  #undef EBSTUBS_START_SEC_VAR_FAST_POWER_ON_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_INIT_32)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_NO_INIT_8)
  #undef EBSTUBS_START_SEC_VAR_SLOW_NO_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_NO_INIT_8)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_NO_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_NO_INIT_16)
  #undef EBSTUBS_START_SEC_VAR_SLOW_NO_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_NO_INIT_16)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_NO_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_NO_INIT_32)
  #undef EBSTUBS_START_SEC_VAR_SLOW_NO_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_NO_INIT_32)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_NO_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_CLEARED_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_SLOW_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_CLEARED_8)
  #undef EBSTUBS_START_SEC_VAR_SLOW_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_CLEARED_8)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_CLEARED_16)
  #undef EBSTUBS_START_SEC_VAR_SLOW_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_CLEARED_16)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_CLEARED_32)
  #undef EBSTUBS_START_SEC_VAR_SLOW_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_CLEARED_32)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8)
  #undef EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16)
  #undef EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32)
  #undef EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_INIT_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_SLOW_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_INIT_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_INIT_8)
  #undef EBSTUBS_START_SEC_VAR_SLOW_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_INIT_8)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_INIT_16)
  #undef EBSTUBS_START_SEC_VAR_SLOW_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_INIT_16)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_INIT_32)
  #undef EBSTUBS_START_SEC_VAR_SLOW_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_INIT_32)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_INIT_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_SLOW_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN)
  #undef EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_INIT_8)
  #undef EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_INIT_16)
  #undef EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_INIT_32)
  #undef EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_NO_INIT_8)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_NO_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_NO_INIT_8)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_NO_INIT_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_NO_INIT_16)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_NO_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_NO_INIT_16)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_NO_INIT_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_NO_INIT_32)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_NO_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_NO_INIT_32)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_NO_INIT_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_CLEARED_8)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_CLEARED_8)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_CLEARED_16)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_CLEARED_16)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_CLEARED_32)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_CLEARED_32)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #undef EBSTUBS_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CODE_FAST)
  #undef EBSTUBS_START_SEC_CODE_FAST
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CODE_FAST)
  #undef EBSTUBS_STOP_SEC_CODE_FAST
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CODE_SLOW)
  #undef EBSTUBS_START_SEC_CODE_SLOW
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CODE_SLOW)
  #undef EBSTUBS_STOP_SEC_CODE_SLOW
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_START_SEC_CODE_LIB)
  #undef EBSTUBS_START_SEC_CODE_LIB
  #undef MEMMAP_ERROR

#elif (defined EBSTUBS_STOP_SEC_CODE_LIB)
  #undef EBSTUBS_STOP_SEC_CODE_LIB
  #undef MEMMAP_ERROR

#endif

/*------------------[MemMap error checking]----------------------------------*/

/*==================[end of file]============================================*/
