/**
 * \file
 *
 * \brief AUTOSAR ApplTemplates
 *
 * This file contains the implementation of the AUTOSAR
 * module ApplTemplates.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

#define EBSTUBS_FUNCENABLED_MCU_SETMODE STD_ON
#define EBSTUBS_FUNCENABLED_MCU_GETRESETRAWVALUE STD_ON
#define EBSTUBS_FUNCENABLED_MCU_GETPLLSTATUS STD_ON
#define EBSTUBS_FUNCENABLED_MCU_INITCLOCK STD_ON
#define EBSTUBS_FUNCENABLED_MCU_INITRAMSECTION STD_ON
#define EBSTUBS_FUNCENABLED_MCU_PERFORMRESET STD_ON
#define EBSTUBS_FUNCENABLED_MCU_DISTRIBUTEPLLCLOCK STD_ON
#define EBSTUBS_FUNCENABLED_MCU_GETRESETREASON STD_ON
#define EBSTUBS_FUNCENABLED_MCU_INIT STD_ON
#define EBSTUBS_FUNCENABLED_MCU_GETVERSIONINFO STD_ON
#define EBSTUBS_FUNCENABLED_MCU_GETRAMSTATE STD_ON
#define EBSTUBS_FUNCENABLED_MCU_GETRESETREASON STD_ON
#define EBSTUBS_FUNCENABLED_MCU_INIT STD_ON
#define EBSTUBS_FUNCENABLED_MCU_PERFORMRESET STD_ON
#define EBSTUBS_FUNCENABLED_MCU_SETMODE STD_ON
#define EBSTUBS_FUNCENABLED_MCU_DISTRIBUTEPLLCLOCK STD_ON
#define EBSTUBS_FUNCENABLED_MCU_GETPLLSTATUS STD_ON
#define EBSTUBS_FUNCENABLED_MCU_GETRAMSTATE STD_ON
#define EBSTUBS_FUNCENABLED_MCU_GETRESETRAWVALUE STD_ON
#define EBSTUBS_FUNCENABLED_MCU_INITRAMSECTION STD_ON
