#if !defined(SCHM_MCUTYPE_H)
#define SCHM_MCUTYPE_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2018 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file is the Module Interlink Types Header which contains the data types relevant for that instance of a basic software module.
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.2.14
  * on Wed Mar 14 01:10:58 CET 2018. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*==================[inclusions]=============================================*/

/*#include <Rte_Type.h>   */  /* RTE Type header file */

/*==================[macros]=================================================*/

/*==================[type definitions]=======================================*/

/*------------------[mode declaration group types]---------------------------*/

#if (!defined RTE_CORE) /* if included by basic software module */

#endif /* (!defined RTE_CORE) */

/*------------------[mode declarations]--------------------------------------*/

#if (!defined RTE_CORE) /* if included by basic software module */

#endif /* (!defined RTE_CORE) */

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */
/** @} doxygen end group definition */
#endif /* !defined(SCHM_MCUTYPE_H) */
/*==================[end of file]============================================*/

