#if !defined(SCHM_DET_H)
#define SCHM_DET_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2016 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file is the Module Interlink Header which contains the declarations relevant for that instance of a basic software module.
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.160
  * on Thu Mar 31 20:05:10 CEST 2016. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*==================[inclusions]=============================================*/

/*==================[macros]=================================================*/

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

extern FUNC(void, RTE_CODE) SchM_Enter_Det_SCHM_DET_EXCLUSIVE_AREA_0(void);

extern FUNC(void, RTE_CODE) SchM_Exit_Det_SCHM_DET_EXCLUSIVE_AREA_0(void);


/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

/** @} doxygen end group definition */
#endif /* !defined(SCHM_DET_H) */
/*==================[end of file]============================================*/

