#ifndef SCHM_PORT_H
#define SCHM_PORT_H
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \version 6.7.3
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2022 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file is the Module Interlink Header which contains the declarations relevant for that instance of a basic software module.
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.7.3
 * on Sun Jun 19 00:43:27 CEST 2022. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Declaration of functions with external linkage]========= */

extern FUNC(void, SCHM_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_00 (void);
extern FUNC(void, SCHM_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_00 (void);
extern FUNC(void, SCHM_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_01 (void);
extern FUNC(void, SCHM_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_01 (void);
extern FUNC(void, SCHM_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_02 (void);
extern FUNC(void, SCHM_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_02 (void);
extern FUNC(void, SCHM_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_03 (void);
extern FUNC(void, SCHM_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_03 (void);
extern FUNC(void, SCHM_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_04 (void);
extern FUNC(void, SCHM_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_04 (void);
extern FUNC(void, SCHM_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_05 (void);
extern FUNC(void, SCHM_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_05 (void);
extern FUNC(void, SCHM_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_06 (void);
extern FUNC(void, SCHM_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_06 (void);
extern FUNC(void, SCHM_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_07 (void);
extern FUNC(void, SCHM_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_07 (void);
extern FUNC(void, SCHM_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_08 (void);
extern FUNC(void, SCHM_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_08 (void);
extern FUNC(void, SCHM_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_09 (void);
extern FUNC(void, SCHM_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_09 (void);
extern FUNC(void, SCHM_CODE) SchM_Enter_Port_PORT_EXCLUSIVE_AREA_10 (void);
extern FUNC(void, SCHM_CODE) SchM_Exit_Port_PORT_EXCLUSIVE_AREA_10 (void);


#endif
/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
